steps:
- name: gcr.io/$PROJECT_ID/helm
  args: ['delete','${_RELEASE_NAME}', '--purge']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
substitutions:
    _RELEASE_NAME: default
    _COMPUTE_ZONE: us-central1-f
    _CONTAINER_CLUSTER: development
logsBucket: 'gs://jv2-design-center_cloudbuild/'