module.exports = {
  id: 1,
  active: true,
  code: '',
  images: [],
  type: '',
  description: '',
  priceRange: [],
  collections: 0,
  isTopProduct: true,
  details: '',
  specs: '',
  name: '',
  customizable: true,
  yotpoId: '',
  yotpoAverageScore: {
    total: 0,
    averageScore: 100
  },
  fitStyles: [],
  genders: [],
  bodyChartId: 0,
  retailMen: true,
  retailWomen: true,
  shortDescription: '',
  genderId: 0,
  sizeRange: [],
  label: '',
  flatlock: '',
  bumpMap: '',
  weight: 0,
  relatedProducts: []
}
