module.exports = {
  id: 1,
  active: true,
  code: '',
  shortId: '',
  images: [],
  contentTile: '',
  type: 'string',
  material_banner: 'string',
  pictures: [],
  mediaFiles: [],
  description: 'string',
  productMaterials: [],
  designCenter: true,
  priceRange: [],
  collections: 1,
  isTopProduct: true,
  relatedItemTag: '',
  categoryName: '',
  details: '',
  specs: '',
  materials: '',
  season: '',
  name: 'My Product',
  customizable: true,
  yotpoId: '',
  yotpoAverageScore: {
    total: 100,
    averageScore: 100
  },
  fitStyles: [],
  genders: [],
  bodyChartId: 1,
  retailMen: true,
  retailWomen: true,
  shortDescription: '',
  genderId: 1,
  productTotal: 1,
  unitPrice: 1,
  sizeRange: [],
  obj: '',
  mtl: '',
  themes: [],
  tags: '',
  label: '',
  sports: [],
  flatlock: '',
  bumpMap: '',
  binding: '',
  zipper: {
    white: '',
    blacl: ''
  },
  bibBrace: {
    white: '',
    black: ''
  },
  weight: 5,
  relatedProducts: [],
  isCustom: true,
  colors: [],
  mpn: ' string'
}
