/**
 * App Global Colors
 */

export const WHITE = '#FFFFFF'
export const WHITE_SMOKE = '#F5F5F5'
export const WHITE_TRANSPARENT = '#FFFFFF96'
export const BLACK = '#000000'
export const BLACK_SHADOW = 'rgba(0, 0, 0, 0.25)'
export const AUBERGINE = '#231F20'
export const GRAY_DARK = '#5F6062'
export const GRAY = '#BEBEBE'
export const GRAY_LIGHT = '#DCDCDC'
export const GRAY_LIGHTEST = '#F1F4F5'
export const GRAY_SNOW = '#FAFAFA'
export const GRAY_SOFT = '#A0A0A0'
export const GRAY_STRONG = '#7C7C7C'
export const GRAY_HEADER = '#f7f7f7'
export const GRAY_SHADOW = 'rgba(120, 120, 120, 0.2)'
export const RED = '#E61737'
export const RED_TRANSPARENT = '#E61737B8'
export const RED_TRANSPARENT_LIGHT = 'rgba(230,23,55,0.03)'
export const BLUE = '#4A90E2'
export const BLUE_BRIGHT = '#4185DE'
export const BLUE_SOFT = '#6EA6E7'
export const BLUE_LIGHT = '#00AFF2'
export const GRAY_DISABLE = '#EFF2F4'
export const BLUE_SHADOW = 'rgba(74, 144, 226, 0.2)'
export const SELECTION_3D_AREA = '#F2F2F2'
export const TRANSPARENT = 'transparent'
export const GREEN = '#24A10B'
export const GREEN_LIGHT = '#D7FFD5'
export const GREEN_BRIGHT = '#6DCE37'
export const GREEN_TRANSPARENT = '#52c41a99'
export const FACEBOOKBLUE = '#395CA9'
export const GOOGLERED = '#F0372D'
export const BLUE_DARK = '#0084FF'
export const DARKER_GRAY = '#8C8C8C'
export const MID_GRAY = '#CCCCCC'
export const BLUE_LIGHTEST = '#eef1f2'
export const BLACK_LIGHT = '#241F20'
export const GRAY_SKELETON = '#eae9e9'
export const GRAY_BLUE = '#d2d2dc'
