/**
 * ArtworkSpecs -  Messages
 */

import { defineMessages } from 'react-intl'

export default defineMessages({
  title: {
    id: 'screens.ArtworkSpecs.tittle',
    defaultMessage: 'ARTWORK SPECS'
  },
  subtitle: {
    id: 'screens.ArtworkSpecs.subtitle',
    defaultMessage: 'A break down of what JAKROO needs when it comes to art…'
  },
  maintitle: {
    id: 'screens.ArtworkSpecs.maintitle',
    defaultMessage:
      'Graphics and logos are usually designed in one of two ways: VECTOR or RASTER'
  },
  vectorWork: {
    id: 'screens.ArtworkSpecs.vectorWork',
    defaultMessage:
      // tslint:disable-next-line:max-line-length
      'VECTOR ARTWORK is designed by plotting points on X/Y coordinates and connecting those points together. Most professional designers create logos in vector for one main reason — they can be re-sized without pixelating. This sample of the JAKROO logo, to the left, shows a logo created in vector format. This logo can be enlarged to any size and the lines will always be crisp and sharp.'
  },
  rasterWork: {
    id: 'screens.ArtworkSpecs.rasterWork',
    defaultMessage:
      // tslint:disable-next-line:max-line-length
      'RASTER ARTWORK is generated by creating a grid of tiny pixels on your computer screen and filling each one of those pixels with a specific color. The pixels are small enough that our eye doesn’t see them as pixels. Raster artwork is created by using a raster-based software, such as Photoshop, which is composed of thousands of little pixels. When our designers try to scale the logo to a larger size, those little pixels become big pixels, therefore resulting in a blurry image. The sample of the JAKROO logo, to the right, will give you an idea as to how the logo will appear if our designers enlarge raster images. JAKROO can’t guarantee the clarity of your artwork if raster images are being used.'
  }
})
