apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "server-chart.fullname" . }}-deployment
  namespace: {{ .Values.project.environment }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "server-chart.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ template "server-chart.fullname" . }}-app
    spec:
      containers:
        - name: app
          image: {{ .Values.deployment.image }}
          ports:
          - containerPort: {{ .Values.deployment.port }}
          env:
            {{- range $key, $value := .Values.env.data }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "server-chart.fullname" . }}-service
  namespace: {{ .Values.project.environment }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "server-chart.fullname" . }}-app
  ports:
    - name: {{ template "server-chart.fullname" . }}-port
      port: {{ .Values.deployment.port }}
      targetPort: {{ .Values.deployment.port }}
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "server-chart.fullname" . }}-ingress
  namespace: {{ .Values.project.environment }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{if .Values.ingress.withCert }}
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    {{end}}
spec:
  tls:
  - hosts:
    - {{if .Values.project.withSubdomain }}
      {{ template "server-chart.fullname" . }}.{{ .Values.project.name }}.{{ .Values.project.domain }}
      {{- else }}
      {{ .Values.project.domain }}
      {{end}}
    secretName: {{ template "server-chart.fullname" . }}-crt-secret
  rules:
  - host: {{if .Values.project.withSubdomain }}
          {{ template "server-chart.fullname" . }}.{{ .Values.project.name }}.{{ .Values.project.domain }}
          {{- else }}
          {{ .Values.project.domain }}
          {{end}}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "server-chart.fullname" . }}-service
            servicePort: {{ .Values.deployment.port }}