{{if .Values.ingress.withCert }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "server-chart.fullname" . }}-crt
spec:
  secretName: {{ template "server-chart.fullname" . }}-crt-secret
  dnsNames:
  - {{if .Values.project.withSubdomain }}
    {{ template "server-chart.fullname" . }}.{{ .Values.project.name }}.{{ .Values.project.domain }}
    {{- else }}
    {{ .Values.project.domain }}
    {{end}}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{if .Values.project.withSubdomain }}
        {{ template "server-chart.fullname" . }}.{{ .Values.project.name }}.{{ .Values.project.domain }}
        {{- else }}
        {{ .Values.project.domain }}
        {{end}}
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
{{end}}